version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app_network

  flask:
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
