name: Build and Push Docker Image   

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: genvangelion/stonqs:backend-latest
    
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: genvangelion/stonqs:frontend-latest

    - name: Build and push Flask Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./flask
        file: ./flask/Dockerfile
        push: true
        tags: genvangelion/stonqs:flask-latest
